# Generated by Django 4.2 on 2023-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(default='localhost', max_length=50)),
                ('port', models.IntegerField(default=27017)),
                ('db_name', models.CharField(default='TCGA', max_length=50)),
                ('collection_name', models.CharField(blank=True, default='', max_length=50)),
                ('descriptions', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
