# Generated by Django 4.2 on 2023-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gene_name', models.CharField(default='', max_length=50)),
                ('ENSEMBL', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('Synonyms', models.TextField(blank=True, default='')),
                ('chromosome', models.CharField(default='', max_length=10)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
