name: Server CI/CD

on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/GEPIA2023-frontend
            git pull
            git checkout frontend
            pnpm i
            pnpm build
            pm2 reload all
